services:
  - type: web
    name: rag-document-qa-api
    runtime: docker
    plan: starter  # Change to 'standard' for production
    region: oregon  # or your preferred region
    branch: main    # or your deployment branch

    # Environment variables (set these in Render dashboard)
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: GEMINI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: VALID_TOKEN
        sync: false  # Set this manually in Render dashboard
      - key: SUPABASE_URL
        sync: false  # Set this manually in Render dashboard
      - key: SUPABASE_KEY
        sync: false  # Set this manually in Render dashboard
      - key: SUPABASE_BUCKET
        value: documents
      - key: EMBEDDING_MODEL_NAME
        value: all-MiniLM-L6-v2
      - key: CHUNK_SIZE
        value: 2000
      - key: CHUNK_OVERLAP
        value: 200
      - key: TOP_K_RETRIEVAL
        value: 10
      - key: MAX_CONTEXT_LENGTH
        value: 10000
      - key: PORT
        value: 8000

    # Health check
    healthCheckPath: /api/v1/health

    # Auto-deploy settings
    autoDeploy: true

    # Build settings
    buildFilter:
      paths:
        - main.py
        - supabase_utils.py
        - requirements.txt
        - Dockerfile
        - render.yaml